# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Node.js CI

on:
  push:
   branches:
     - master
  pull_request:
   branches:
     - master

jobs:
  build:
    name: CLI
    runs-on: ubuntu-latest

    strategy:
     matrix:
       os: [ubuntu-latest]
       node: [10, 12, 14]
    
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node }}
      - run: yarn run test
